trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  workingDirectory: 'angular-app'

stages:
  - stage: Build
    jobs:
      - job: BuildJob
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '16.x'
            displayName: 'Install Node.js'

          - script: |
              npm install
              npm run build --prod
            displayName: 'Build the application'
            workingDirectory: $(workingDirectory)

          - script: |
              zip -r $(Build.ArtifactStagingDirectory)/angular-app.zip dist/
            displayName: 'Zip the files'
            workingDirectory: $(workingDirectory)

          - script: |
              ls -alh $(Build.ArtifactStagingDirectory)
            displayName: 'List build artifacts'

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)/angular-app.zip'
              ArtifactName: 'angular-app'
              publishLocation: 'container'
            displayName: 'Create and publish artifact'


