trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: |
    cd angular-app
    npm install
  displayName: 'Install dependencies'

- script: |
    cd angular-app
    npm run build -- --prod
  displayName: 'Build Angular project'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'angular-app/dist/angular-app'
    ArtifactName: 'AngularApp'  # Removed the extraneous 'a' from the end
    publishLocation: 'Container'
  displayName: 'Publish Build Artifacts'
