trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: |
    cd FrontendAngularTesting/angular-app
    npm install
  displayName: 'Install dependencies'

- script: |
    cd FrontendAngularTesting/angular-app
    npm run build -- --prod
  displayName: 'Build Angular project'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'FrontendAngularTesting/angular-app/dist/angular-app'
    ArtifactName: 'AngularApp'
    publishLocation: 'Container'
  displayName: 'Publish Build Artifacts'
