trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: |
    pwd
    ls -la
    if [ -d "FrontendAngularTesting/angular-app" ]; then
      cd FrontendAngularTesting/angular-app
      npm install
    else
      echo "Directory FrontendAngularTesting/angular-app does not exist."
      exit 1
    fi
  displayName: 'Install dependencies'

- script: |
    if [ -d "FrontendAngularTesting/angular-app" ]; then
      cd FrontendAngularTesting/angular-app
      npm run build -- --prod
    else
      echo "Directory FrontendAngularTesting/angular-app does not exist."
      exit 1
    fi
  displayName: 'Build Angular project'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'FrontendAngularTesting/angular-app/dist/angular-app'
    ArtifactName: 'AngularApp'
    publishLocation: 'Container'
  displayName: 'Publish Build Artifacts'
