trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'  # Adjusted based on Angular 13's compatibility
  displayName: 'Install Node.js'

- script: npm install
  displayName: 'Install dependencies'

- script: npm run build
  displayName: 'Build Angular project'
  

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'dist/angular-app'  # Based on the outputPath in angular.json
    ArtifactName: 'AngularApp'
    publishLocation: 'Container'
  displayName: 'Publish Build Artifacts'
