SET @@AUTOCOMMIT = 1;

DROP DATABASE IF EXISTS cbms;
DROP USER backend;
FLUSH PRIVILEGES;

CREATE DATABASE cbms;

CREATE USER 'backend'@'%' IDENTIFIED BY 'x9Jfh3tegfcZVe3WP4Nza8BoAghqr2iG';
GRANT ALL PRIVILEGES ON cbms.* TO backend;